
package com.mrjaffesclass.apcs.mvc.template;
import com.mrjaffesclass.apcs.messenger.*;
/**
 * MVC Template
 * This is a template of an MVC framework used by APCS for the 
 * PDA project
 * 
 * Please note...in the instructions...it says that it should
 * utilize an MVC framework. Utilize means "to make practical 
 * and effective use of" and since making this use the model
 * (since we are already using the controller and view, it 
 * would not be practical nor an effective use of code or time.
 * 
 * @author Rebekah Leslie and Ann Tran
 * @version 1.3
 */
public class View extends javax.swing.JFrame implements MessageHandler {
  private final Messenger mvcMessaging;
  /**
   * Creates a new view
   * @param messages mvcMessaging object
   */
  public View(Messenger messages) {
    mvcMessaging = messages;   // Save the calling controller instance
    initComponents();           // Create and init the GUI components
  }
  /**
   * Initialize the model here and subscribe
   * to any required messages
   */
  public void init() {
    // Subscribe to messages here
    mvcMessaging.subscribe("model:lowerOfficial:view", this);
    mvcMessaging.subscribe("model:upperOfficial:view", this);
    jLabel1.setVisible(false);
    jLabel2.setVisible(false);
  }
  @Override
  public void messageHandler(String messageName, Object messagePayload) {
    if (messagePayload != null) {
      System.out.println("RCV (view): "+messageName+" | "+messagePayload.toString());
    } else {
      System.out.println("RCV (view): "+messageName+" | No data sent");
    }
    if (messageName.equals("model:variable1Changed")) {
      //jLabel1.setText(messagePayload.toString());
    } else {
      //jLabel2.setText(messagePayload.toString());      
    }
  }
  /**
   * Instantiate an object with the field number that was clicked (1 or 2) and
   * the direction that the number should go (up or down)
   * @param fieldNumber 1 or 2 for the field being modified
   * @param direction this.UP (1) or this.DOWN (-1), constants defined above
   * @return the HashMap payload to be sent with the message
   */
  private MessagePayload createPayload(int fieldNumber, int direction) {
    MessagePayload payload = new MessagePayload(fieldNumber, direction);
    return payload;
  }
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        name = new javax.swing.JPanel();
        firstLabel = new javax.swing.JLabel();
        lastLabel = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        age = new javax.swing.JPanel();
        ageLabel = new javax.swing.JLabel();
        ageNumber = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        firstAndLast = new javax.swing.JTextField();
        resetButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        findAgeRange = new javax.swing.JButton();
        lowerBound = new javax.swing.JLabel();
        to = new javax.swing.JLabel();
        upperBound = new javax.swing.JLabel();
        doubleChecking = new javax.swing.JPanel();
        questionForDate = new javax.swing.JLabel();
        dateAge = new javax.swing.JTextField();
        truth = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        name.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        firstLabel.setText("First Name:");

        lastLabel.setText("Last Name:");

        javax.swing.GroupLayout nameLayout = new javax.swing.GroupLayout(name);
        name.setLayout(nameLayout);
        nameLayout.setHorizontalGroup(
            nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstLabel)
                    .addComponent(lastLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastName)
                    .addComponent(firstName))
                .addContainerGap())
        );
        nameLayout.setVerticalGroup(
            nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstLabel)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastLabel)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        age.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Age", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        ageLabel.setText("How Old Are You? (In Years):");

        ageNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageNumberActionPerformed(evt);
            }
        });
        ageNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageNumberKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout ageLayout = new javax.swing.GroupLayout(age);
        age.setLayout(ageLayout);
        ageLayout.setHorizontalGroup(
            ageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ageNumber)
                .addContainerGap())
        );
        ageLayout.setVerticalGroup(
            ageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(ageNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        title.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("PERMISSIBLE DATING AGE");

        firstAndLast.setEditable(false);
        firstAndLast.setText(" ");
        firstAndLast.setBorder(null);

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        findAgeRange.setText("Click Here To Find Your Age Range :)");
        findAgeRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findAgeRangeActionPerformed(evt);
            }
        });

        lowerBound.setText("          ");

        to.setText("          ");

        upperBound.setText("          ");

        doubleChecking.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Just To Make Sure...", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        questionForDate.setText("What is the age of your possible date?");

        dateAge.setText(" ");
        dateAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dateAgeKeyTyped(evt);
            }
        });

        truth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        truth.setText(" ");

        jButton1.setText("Click Here To Double Check If Your Date's Age is Permissible :)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout doubleCheckingLayout = new javax.swing.GroupLayout(doubleChecking);
        doubleChecking.setLayout(doubleCheckingLayout);
        doubleCheckingLayout.setHorizontalGroup(
            doubleCheckingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doubleCheckingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(doubleCheckingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                    .addGroup(doubleCheckingLayout.createSequentialGroup()
                        .addComponent(questionForDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateAge))
                    .addGroup(doubleCheckingLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(truth, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        doubleCheckingLayout.setVerticalGroup(
            doubleCheckingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doubleCheckingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(doubleCheckingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(questionForDate)
                    .addComponent(dateAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(truth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\PDA\\PDA Project Netbeans 4\\Thumbsup.png")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("F:\\PDA\\PDA Project Netbeans 4\\ThumbsDown.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(firstAndLast)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lowerBound)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(to)
                                .addGap(8, 8, 8)
                                .addComponent(upperBound))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(resetButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(exitButton))
                            .addComponent(doubleChecking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(findAgeRange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(age, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstAndLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lowerBound)
                            .addComponent(to)
                            .addComponent(upperBound))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(findAgeRange)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(doubleChecking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(resetButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        firstName.setText(" ");
        lastName.setText(" ");
        ageNumber.setText(" ");
        firstAndLast.setText(" ");
        lowerBound.setText(" ");
        upperBound.setText(" ");
        to.setText(" ");
        dateAge.setText(" ");
        truth.setText(" ");
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void findAgeRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findAgeRangeActionPerformed
        float ageAmount, lower, diff, upper;
        String fullName, statement;
        ageAmount = Float.parseFloat(ageNumber.getText());  
        lower = ageAmount/2 + 7;
        diff = ageAmount - lower;
        upper = (ageAmount-7)*2;
        lowerBound.setText(String.valueOf(lower)); 
        upperBound.setText(String.valueOf(upper)); 
        to.setText(" to "); 
        fullName = firstName.getText() + " " + lastName.getText();
        if(fullName!=null){
          statement = fullName + " your dating range is:";
        }else{
          statement = "Your dating range is:";  
        }
        if(ageAmount > 14){
            firstAndLast.setText(statement);
        }
        else {
            firstAndLast.setText("Wait until you're older to date!");
        }
    }//GEN-LAST:event_findAgeRangeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        float dateAgeAmount, ageAmount, lower, diff, upper;
        ageAmount = Float.parseFloat(ageNumber.getText());
        lower = ageAmount/2 + 7;
        diff = ageAmount - lower;
        upper = ageAmount + diff;
        dateAgeAmount = Float.parseFloat(dateAge.getText());
        if(dateAgeAmount > 14){
            if((dateAgeAmount <= upper)&&(dateAgeAmount >= lower)){
                truth.setText("Your date is in your range.");
                jLabel2.setVisible(false);
                jLabel1.setVisible(true);}
            else{
                truth.setText("I'm sorry. Your date isn't in your range.");
                jLabel1.setVisible(false);
                jLabel2.setVisible(true);}
        }
        else{
            truth.setText("Your date is too young. Calling authorities");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ageNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageNumberActionPerformed

    }//GEN-LAST:event_ageNumberActionPerformed

    private void ageNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageNumberKeyTyped
        char e = evt.getKeyChar();
        if(!Character.isDigit(e))
        {
            evt.consume();
        }
    }//GEN-LAST:event_ageNumberKeyTyped

    private void dateAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateAgeKeyTyped
        char e = evt.getKeyChar();
        if(!Character.isDigit(e))
        {
            evt.consume();
        }
    }//GEN-LAST:event_dateAgeKeyTyped

  /**
   * @param args the command line arguments
   */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel age;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageNumber;
    private javax.swing.JTextField dateAge;
    private javax.swing.JPanel doubleChecking;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton findAgeRange;
    private javax.swing.JTextField firstAndLast;
    private javax.swing.JLabel firstLabel;
    private javax.swing.JTextField firstName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lastLabel;
    private javax.swing.JTextField lastName;
    private javax.swing.JLabel lowerBound;
    private javax.swing.JPanel name;
    private javax.swing.JLabel questionForDate;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel title;
    private javax.swing.JLabel to;
    private javax.swing.JLabel truth;
    private javax.swing.JLabel upperBound;
    // End of variables declaration//GEN-END:variables
}